### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by dionverbeke** [tinted-theming/ribboncurls#10]
[data.yaml.txt](https://github.com/user-attachments/files/17043369/data.yaml.txt)
[test.html.txt](https://github.com/user-attachments/files/17043370/test.html.txt)

Description: Nested NOT operator in a loop gives "Error: missing end tag" , 
but looking at the mustache spec this should be allowed.

Commands used:
ribboncurls render -f data.yaml.txt test.html.txt

**Comment by JamyGolden** [comment]
@dionverbeke thanks for reporting, I’ll have a look at this bug this week. Can you provide basic mustache template code that gives the issue? (I know you described but would be good to have this when I look at the bug)

**Comment by dionverbeke** [comment]
> @dionverbeke thanks for reporting, I’ll have a look at this bug this week. Can you provide basic mustache template code that gives the issue? (I know you described it but would be good to have this when I look at the bug)

I have edited the article to add template files to replicate the issue.

**Comment by JamyGolden** [comment]
I've fixed the bug (and added a nested inverted-section to a test), it is out with release `0.4.1`. Let me know if you run into any issues with it.
