### ISSUE TITLE
[Question] Please bump docs.rs version to 0.3.2

### ISSUE THREAD

**Issue by dionverbeke** [tinted-theming/ribboncurls#9]
### **What version of `ribboncurls` are you using?**
0.3.1 and . notation does not work

**Comment by JamyGolden** [comment]
Can you give me example code where I can recreate the issue?

**Comment by dionverbeke** [comment]
This works in 0.2.1, but not in 3.1. So I am sure something has changed
outside of my code.

the json is :

{"users":[{"a":"╨░╨▒╨╡╤é╨║╨░","b":"alphabet","id":1,"lesson":"0"},{"a":"╨É╨▓╤ü╤é╤Ç╨░╨╗╤û╤Å","b":"Australia","id":2,"lesson":"0"},{"a":"╨░╨┤╤Ç╨╡╤ü╨░","b":"address","id":3,"lesson":"0"},{"a":"╨░╨║╤é╨╛╤Ç","b":"actor","id":4,","b":"actor","id":4,"lesson":"0"},{"a":"╨░╨╗╤ä╨░╨▓╤û╤é","b":"alphabet","id":5,"lesson":"0"},{"a":"╨É╨╝╨╡╤Ç╨╕╨║╨░","b":"America","id":6,"lesson":"0"},{"a":"╨░╨╜╨│╨╗╤û╨╣╤ü╤î╨║╨░","b":"English","id":7,"lesson":"0"},{"a":"╨░╨╜╨║╨╡╤é╨░","b":"questionnaire","id":8,"lesson":"0"},{"a":"╨▒╨░╨╗╨╡╤é","b":"ballet","id":9,"lesson":"0"},{"a":"╨▒╤û╨╖╨╜╨╡╤ü╨╝╨╡╨╜","b":"businessman","id":10,"lesson":"0"},{"a":"╨æ╤Ç╨░╨╖╨╕╨╗╤û╤Å","b":"Brazil","id":11,"lesson":"0"},{"a":"╨▒╤Ç╨░╨╖╨╕╨╗╤î╤ü╤î╨║╨░","b":"Brazilian","id":12,"lesson":"0"},{"a":"╨▒╤â╨┤╨╕╨╜╨╛╨║","b":"house","id":13,"lesson":"0"},{"a":"╨▒╤â╨║╨▓╨░","b":"letter","id":14,"lesson":"0"},{"a":"╨Æ╨╡╨╗╨╕╨║╨╛╨▒╤Ç╨╕╤é╨░╨╜╤û╤Å","b":"United
Kingdom","id":15,"lesson":"0"}]}

<div class="rounded-xl border bg-gray-900">
    <table class="w-full divide-y divide-gray-300">
        <thead>
            <tr>
                <th scope="col" class="p-3">Id</th>
                <th scope="col" class="p-3">Lesson</th>
                <th scope="col" class="p-3">Word</th>
                <th scope="col" class="p-3">Description</th>

            </tr>
        </thead>
        <tbody class="divide-y divide-gray-300">
            {{#users}}
            <tr>
                <td class="p-3">{{.id}}</td>
                <td class="p-3">{{.lesson}}</td>
                <td class="p-3">{{.a}}</td>
                <td class="p-3">{{.b}}</td>
            </tr>
            {{/users}}
        </tbody>
    </table>
</div>

let result = parse_template(String::from("vocabulary.html"), args);

pub fn parse_template(text: String, args: String) -> String {
    let path: std::path::PathBuf = ["templates", text.as_str()].iter().
collect();
    let name = String::from(path.to_str().unwrap());
    // load from file into string
    let file_contents = fs::read_to_string(name).unwrap();

    let partials = parse_partials();
    let result =
        ribboncurls::render(&file_contents, args.as_str(), Some(partials.
as_str())).unwrap();

    result
}

Dion Verbeke

*Junai Services*

*Sustainable by Design*Mobile: +32 472 63 55 50

**Comment by JamyGolden** [comment]
I can't get your example to work with ribboncurls `0.2.1`. I'm guessing the data you're providing is slightly modified for this github issue though, it contains duplicate keys which isn't valid json; because of this `serde_yaml` treats the provided data as a `Value::String` rather than a `Value::Mapping`. Can you try running the json through a lint and see if the updated data solves the issue? https://jsonlint.com/

**Comment by dionverbeke** [comment]
Solved. That was the issue.

**Comment by JamyGolden** [comment]
Great! I’ll look at adding support for linting or debugging to make this issue more easily visible.
